-- Offline, static assurance review record.
SELECT
  'p03-full-000915' AS artifact_id,
  'p03-src-000915' AS source_record,
  'p03-primary-05' AS scope,
  'Cobalt Harbor' AS organization,
  '2026-07-13' AS review_date,
  'RISK-031' AS risk_reference,
  'AC-27 relates to evidence set 184' AS relationship,
  'no upstream dependency' AS dependency_context,
  'How should a conflicting source be handled before the disposition is recorded?' AS evidence_question,
  'named control owner retained approval boundary for this review.' AS source_facts,
  'A repeated control statement does not establish operation when no counterexample was considered.' AS counterexample,
  'incident chronology' AS evidence_instrument,
  'the record explained why an exception remained open' AS review_observation,
  'a local conclusion was checked for reliance on external access' AS challenge_performed,
  '["the evidence set was collected during the follow-up review", "the evidence custodian confirmed the record boundary", "the reviewer sampled a routine operating condition", "the source fact supported acceptance without qualification", "the comparison used the current control objective", "the evidence was retained in the review register", "the exception path was not invoked", "the reviewer assessed a handover impact", "the decision was suitable for targeted follow-up", "the source chronology contained a reconciled late entry", "the control claim was independently corroborated", "the review boundary excluded unavailable material", "the next assurance trigger is the scheduled review", "the disposition was communicated to the owner", "the retained rationale supports repeat review", "the record remains a local offline assurance artifact"]' AS review_profile,
  'Reject unsupported claims and retain a concise explanation of the missing fact for the next review cycle.' AS decision_rule,
  'accepted with a retained review note' AS disposition,
  'No Kio capability is used or required for this offline review.' AS operating_boundary;
