-- Offline, static assurance review record.
SELECT
  'p03-full-006116' AS artifact_id,
  'p03-src-006116' AS source_record,
  'p03-secondary-02' AS scope,
  'Cobalt Harbor' AS organization,
  '2026-07-20' AS review_date,
  'RISK-031' AS risk_reference,
  'AC-27 relates to evidence set 184' AS relationship,
  'no upstream dependency' AS dependency_context,
  'How does the review distinguish complete evidence from an unsupported assertion?' AS evidence_question,
  'named control owner retained approval boundary for this review.' AS source_facts,
  'A dated narrative without a named custodian is insufficient because responsibility cannot be tested.' AS counterexample,
  'control narrative comparison' AS evidence_instrument,
  'the local conclusion did not depend on a portal or live endpoint' AS review_observation,
  'a compensating action was checked for accountable ownership' AS challenge_performed,
  '["the evidence set was collected before the approval meeting", "the accountable owner confirmed the operating boundary", "the reviewer sampled an adverse operating condition", "the source fact supported acceptance without qualification", "the comparison used the prior review conclusion", "the evidence was retained with the decision record", "the exception path was considered and recorded", "the reviewer assessed a handover impact", "the decision was suitable for targeted follow-up", "the source chronology contained a reconciled late entry", "the control claim was corroborated by a compensating observation", "the review boundary excluded unavailable material", "the next assurance trigger is completion of the follow-up action", "the disposition was communicated to the owner", "the retained rationale supports repeat review", "the record remains a local offline assurance artifact"]' AS review_profile,
  'Reject unsupported claims and retain a concise explanation of the missing fact for the next review cycle.' AS decision_rule,
  'accepted with a retained review note' AS disposition,
  'No Kio capability is used or required for this offline review.' AS operating_boundary;
