-- Offline, static assurance review record.
SELECT
  'p03-full-007948' AS artifact_id,
  'p03-src-007948' AS source_record,
  'p03-primary-09' AS scope,
  'Cobalt Harbor' AS organization,
  '2026-07-13' AS review_date,
  'RISK-031' AS risk_reference,
  'AC-27 relates to evidence set 184' AS relationship,
  'no upstream dependency' AS dependency_context,
  'Which source fact would cause the reviewer to accept the control conclusion?' AS evidence_question,
  'named control owner retained approval boundary for this review.' AS source_facts,
  'A generic assurance claim is rejected when it cannot be traced to an owner, date, and retained evidence.' AS counterexample,
  'outcome verification note' AS evidence_instrument,
  'the evidence set included a challenge from outside the delivery team' AS review_observation,
  'a scope boundary was compared with the evidence collection boundary' AS challenge_performed,
  '["the evidence set was collected before the approval meeting", "the accountable owner confirmed the operating boundary", "the reviewer sampled an adverse operating condition", "the source fact supported acceptance with a documented caveat", "the comparison used the prior review conclusion", "the evidence was retained in the review register", "the exception path was not invoked", "the reviewer found no handover impact", "the decision was suitable for targeted follow-up", "the source chronology contained a reconciled late entry", "the control claim was corroborated by a compensating observation", "the review boundary identified unavailable material as a limitation", "the next assurance trigger is completion of the follow-up action", "the disposition was communicated to the owner", "the retained rationale supports repeat review", "the record remains a local offline assurance artifact"]' AS review_profile,
  'Treat the control as effective only when the counterexample has been considered and the exception path is explicit.' AS decision_rule,
  'accepted with a retained review note' AS disposition,
  'No Kio capability is used or required for this offline review.' AS operating_boundary;
