# Alpha threshold audit

Synthetic calibration memo for Helix Forge Lab’s Model Alpha M-14 / R184, dated 2026-07-13. The figures below are aggregate and reproducible in this notebook.

In [1]:
grid = [(0.50, 0.881, 0.865), (0.55, 0.889, 0.852), (0.60, 0.898, 0.831)]
for threshold, precision, recall in grid:
    f1 = 2 * precision * recall / (precision + recall)
    print(f"threshold {threshold:.2f}: precision {precision:.3f}, recall {recall:.3f}, F1 {f1:.3f}")

threshold 0.50: precision 0.881, recall 0.865, F1 0.873
threshold 0.55: precision 0.889, recall 0.852, F1 0.870
threshold 0.60: precision 0.898, recall 0.831, F1 0.863


## Decision

The 0.50 operating point is retained for the current synthetic audit: it reproduces the recorded R184 precision **0.881**, recall **0.865**, and F1 **0.873**. Increasing the threshold improves precision but lowers recall enough to reduce the rounded F1.

No user-level scores, raw prompts, or external services are used.

In [2]:
round(2 * 0.881 * 0.865 / (0.881 + 0.865), 3) == 0.873

True