-- Offline, static assurance review record.
SELECT
  'p03-full-007147' AS artifact_id,
  'p03-src-007147' AS source_record,
  'p03-primary-08' AS scope,
  'Cobalt Harbor' AS organization,
  '2026-07-14' AS review_date,
  'RISK-031' AS risk_reference,
  'AC-27 relates to evidence set 184' AS relationship,
  'no upstream dependency' AS dependency_context,
  'How should a conflicting source be handled before the disposition is recorded?' AS evidence_question,
  'change sponsor retained implementation record for this review.' AS source_facts,
  'A repeated control statement does not establish operation when no counterexample was considered.' AS counterexample,
  'handover checklist' AS evidence_instrument,
  'the verification date was visible beside the source fact' AS review_observation,
  'a local conclusion was checked for reliance on external access' AS challenge_performed,
  '["the evidence set was collected during the follow-up review", "the evidence custodian confirmed the record boundary", "the reviewer sampled a routine operating condition", "the source fact supported acceptance with a documented caveat", "the comparison used the prior review conclusion", "the evidence was retained with the decision record", "the exception path was considered and recorded", "the reviewer assessed a handover impact", "the decision was suitable for targeted follow-up", "the source chronology contained a reconciled late entry", "the control claim was independently corroborated", "the review boundary identified unavailable material as a limitation", "the next assurance trigger is completion of the follow-up action", "the disposition was communicated to the owner", "the retained rationale supports repeat review", "the record remains a local offline assurance artifact"]' AS review_profile,
  'Record an approval only after the reviewer can reproduce the conclusion from the retained facts without network access.' AS decision_rule,
  'accepted with a retained review note' AS disposition,
  'No Kio capability is used or required for this offline review.' AS operating_boundary;
