-- Offline, static assurance review record.
SELECT
  'p03-full-002048' AS artifact_id,
  'p03-src-002048' AS source_record,
  'p03-primary-04' AS scope,
  'Cobalt Harbor' AS organization,
  '2026-07-15' AS review_date,
  'RISK-031' AS risk_reference,
  'AC-27 relates to evidence set 184' AS relationship,
  'no upstream dependency' AS dependency_context,
  'What decision can be made from the retained source material without external access?' AS evidence_question,
  'records owner retained disposition record for this review.' AS source_facts,
  'A dated narrative without a named custodian is insufficient because responsibility cannot be tested.' AS counterexample,
  'risk treatment worksheet' AS evidence_instrument,
  'the review showed how contradictory evidence was resolved' AS review_observation,
  'a corrective action was tested for closure evidence' AS challenge_performed,
  '["the evidence set was collected before the approval meeting", "the accountable owner confirmed the operating boundary", "the reviewer sampled a routine operating condition", "the source fact supported acceptance without qualification", "the comparison used the prior review conclusion", "the evidence was retained in the review register", "the exception path was not invoked", "the reviewer found no handover impact", "the decision was suitable for routine monitoring", "the source chronology was complete", "the control claim was independently corroborated", "the review boundary identified unavailable material as a limitation", "the next assurance trigger is the scheduled review", "the disposition was communicated to the owner", "the retained rationale supports repeat review", "the record remains a local offline assurance artifact"]' AS review_profile,
  'Approve when the evidence is specific, attributable, and dated; otherwise classify the item as needing corroboration.' AS decision_rule,
  'accepted with a retained review note' AS disposition,
  'No Kio capability is used or required for this offline review.' AS operating_boundary;
