-- Offline, static assurance review record.
SELECT
  'p03-full-009883' AS artifact_id,
  'p03-src-009883' AS source_record,
  'p03-secondary-04' AS scope,
  'Cobalt Harbor' AS organization,
  '2026-07-14' AS review_date,
  'RISK-031' AS risk_reference,
  'AC-27 relates to evidence set 184' AS relationship,
  'no upstream dependency' AS dependency_context,
  'What observable evidence demonstrates that the stated control objective is met?' AS evidence_question,
  'risk owner retained decision record for this review.' AS source_facts,
  'A generic assurance claim is rejected when it cannot be traced to an owner, date, and retained evidence.' AS counterexample,
  'exception ageing report' AS evidence_instrument,
  'the exception route was visible to an independent reviewer' AS review_observation,
  'an unsupported completion status was tested for underlying proof' AS challenge_performed,
  '["the evidence set was collected during the follow-up review", "the evidence custodian confirmed the record boundary", "the reviewer sampled a routine operating condition", "the source fact supported acceptance with a documented caveat", "the comparison used the current control objective", "the evidence was retained in the review register", "the exception path was not invoked", "the reviewer assessed a handover impact", "the decision was suitable for routine monitoring", "the source chronology contained a reconciled late entry", "the control claim was corroborated by a compensating observation", "the review boundary excluded unavailable material", "the next assurance trigger is the scheduled review", "the disposition was communicated to the independent reviewer", "the retained rationale supports repeat review", "the record remains a local offline assurance artifact"]' AS review_profile,
  'Record an approval only after the reviewer can reproduce the conclusion from the retained facts without network access.' AS decision_rule,
  'accepted with a retained review note' AS disposition,
  'No Kio capability is used or required for this offline review.' AS operating_boundary;
