apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkout-svc17
  namespace: northstar-observability
  labels:
    app.kubernetes.io/name: checkout-svc17
    app.kubernetes.io/part-of: northstar-transit-cloud
    monitoring.northstar.example/stack: regional-prometheus
spec:
  namespaceSelector:
    matchNames: [northstar-production]
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout-svc17
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: false
